In [4]:
import math
import numpy as np
from numpy import linalg

In [5]:
smalltri = '\
75 \
95 64 \
17 47 82 \
18 35 87 10 \
20 04 82 47 65 \
19 01 23 75 03 34 \
88 02 77 73 07 63 67 \
99 65 04 28 06 16 70 92 \
41 41 26 56 83 40 80 70 33 \
41 48 72 33 47 32 37 16 94 29 \
53 71 44 65 25 43 91 52 97 51 14 \
70 11 33 28 77 73 17 78 39 68 17 57 \
91 71 52 38 17 14 91 43 58 50 27 29 48 \
63 66 04 68 89 53 67 30 73 16 69 87 40 31 \
04 62 98 27 23 09 70 98 73 93 38 53 60 04 23 '

In [6]:
tinytri = '\
3 \
7 4 \
2 4 6 \
8 5 9 3 '

In [7]:
print(len(smalltri))

360


In [8]:
#I'm less worried about finding an efficient algorithm than putting the 100 row .txt file into a variable
x = 0
listy =[]
while x <= len(smalltri)-3:
    listy += [int(smalltri[x:x+3])]
    x+=3
print(len(listy))
print(listy[len(listy)-1])

120
23


In [10]:
smalltri1 = np.zeros((15,15), dtype = int)
print(smalltri1)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [11]:
x = 0
for i in range(0,15):
    for j in range (0,i+1):
        smalltri1[i,j] = listy[x]
        x+=1
print(smalltri1)

[[75  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [95 64  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [17 47 82  0  0  0  0  0  0  0  0  0  0  0  0]
 [18 35 87 10  0  0  0  0  0  0  0  0  0  0  0]
 [20  4 82 47 65  0  0  0  0  0  0  0  0  0  0]
 [19  1 23 75  3 34  0  0  0  0  0  0  0  0  0]
 [88  2 77 73  7 63 67  0  0  0  0  0  0  0  0]
 [99 65  4 28  6 16 70 92  0  0  0  0  0  0  0]
 [41 41 26 56 83 40 80 70 33  0  0  0  0  0  0]
 [41 48 72 33 47 32 37 16 94 29  0  0  0  0  0]
 [53 71 44 65 25 43 91 52 97 51 14  0  0  0  0]
 [70 11 33 28 77 73 17 78 39 68 17 57  0  0  0]
 [91 71 52 38 17 14 91 43 58 50 27 29 48  0  0]
 [63 66  4 68 89 53 67 30 73 16 69 87 40 31  0]
 [ 4 62 98 27 23  9 70 98 73 93 38 53 60  4 23]]


i suppose the way to go about this is by improving
I need the answer to check if clever methods work so I guess a brute force method is a good control
There was already a problem regarding the number of possible paths down a triangle, I'd do well to remember my logic
I know that I am looking at a series of binary choices
2^14
I can think of infinitely many ways to make it more likely to find a good path. However I can't think of any to guarantee that greatest path.


In [16]:
print('Number of possible paths:',2**14)
print('Imagine an array of length fourteen each entry of which can contain a 1 or 0')

Number of possible paths: 16384
Imagine an array of length fourteen each entry of which can contain a 1 or 0


In [36]:
def binarraygenerator(n):
    binarr = np.zeros(14,dtype=int)
    i = 0
    while n > 2**i:
        i+=1
    while i > -1:
        if n >= 2**i:
            binarr[-i-1]=1
            n = n-(2**i)
        i-=1
    return binarr

In [43]:
print(binarraygenerator(1074))

[0 0 0 1 0 0 0 0 1 1 0 0 1 0]


In [67]:
greatestsum = 0
bestarr= np.empty(15,dtype=int)
binarr = np.empty(14,dtype=int)

In [70]:
for i in range (0,2**14-1):
    currarr = np.zeros(15,dtype=int)
    currarr[0]=75
    x = binarraygenerator(i)
    k = 0
    for j in range(1,15):
        k+= x[j-1]
        currarr[j] = smalltri1[j,k]
    if sum(currarr)>greatestsum:
        greatestsum = sum(currarr)
        bestarr[:]=currarr
        binarr[:]=x
print('Answer to problem 18:', greatestsum)

Answer to problem 18: 1074


In [69]:
print(15*99)
print(bestarr)
print(k)
print(binarr)

1485
[75 64 82 87 82 75 73 28 83 32 91 78 58 73 93]
13
[1 1 0 0 1 0 0 1 1 1 1 1 0 1]


In [58]:
arr1 = np.array([1,2,3])
arr2 = arr1
arr2 +=3
print (arr1)

[4 5 6]
