# Project Euler

Problems 11-20 Annotated by Everett Waterman

In [8]:
import math
import numpy as np

Problem 11

In the 20×20 grid below, four numbers along a diagonal line have been marked in red.<br>

08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08<br>
49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00<br>
81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65<br>
52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91<br>
22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80<br>
24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50<br>
32 98 81 28 64 23 67 10 <span style="color:red">26</span> 38 40 67 59 54 70 66 18 38 64 70<br>
67 26 20 68 02 62 12 20 95 <span style="color:red">63</span> 94 39 63 08 40 91 66 49 94 21<br>
24 55 58 05 66 73 99 26 97 17 <span style="color:red">78</span> 78 96 83 14 88 34 89 63 72<br>
21 36 23 09 75 00 76 44 20 45 35 <span style="color:red">14</span> 00 61 33 97 34 31 33 95<br>
78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92<br>
16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57<br>
86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58<br>
19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40<br>
04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66<br>
88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69<br>
04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36<br>
20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16<br>
20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54<br>
01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48<br>

The product of these numbers is 26 × 63 × 78 × 14 = 1788696.<br>

What is the greatest product of four adjacent numbers in the same direction (up, down, left, right, or diagonally) in the 20×20 grid?

In [1]:
largegrid = '\
08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08 \
49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00 \
81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65 \
52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91 \
22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80 \
24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50 \
32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70 \
67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21 \
24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72 \
21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95 \
78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92 \
16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57 \
86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58 \
19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40 \
04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66 \
88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69 \
04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36 \
20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16 \
20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54 \
01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48 '

In [10]:
print(len(largegrid))
print(1200/20)
print(int(largegrid[0:3]))

1200
60.0
8


In [5]:
arr1 = np.ones((20*20), dtype = int)
x = 0
y = 0
while x < 1200 - 2:
    arr1[y]*=int(largegrid[x:x+3])
    y+=1
    x+=3
arr2 = arr1.reshape([20,20])
print(arr2.shape)
print('\nLook at my pretty array:\n')
print(arr2)

(20, 20)

Look at my pretty array:

[[ 8  2 22 97 38 15  0 40  0 75  4  5  7 78 52 12 50 77 91  8]
 [49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48  4 56 62  0]
 [81 49 31 73 55 79 14 29 93 71 40 67 53 88 30  3 49 13 36 65]
 [52 70 95 23  4 60 11 42 69 24 68 56  1 32 56 71 37  2 36 91]
 [22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80]
 [24 47 32 60 99  3 45  2 44 75 33 53 78 36 84 20 35 17 12 50]
 [32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70]
 [67 26 20 68  2 62 12 20 95 63 94 39 63  8 40 91 66 49 94 21]
 [24 55 58  5 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72]
 [21 36 23  9 75  0 76 44 20 45 35 14  0 61 33 97 34 31 33 95]
 [78 17 53 28 22 75 31 67 15 94  3 80  4 62 16 14  9 53 56 92]
 [16 39  5 42 96 35 31 47 55 58 88 24  0 17 54 24 36 29 85 57]
 [86 56  0 48 35 71 89  7  5 44 44 37 44 60 21 58 51 54 17 58]
 [19 80 81 68  5 94 47 69 28 73 92 13 86 52 17 77  4 89 55 40]
 [ 4 52  8 83 97 35 99 16  7 97 57 32 16 26 26 79 33 27 98 66]
 [88 36 68 87 57 62

In [ ]:
print(arr1[399])
print(arr2[19,19])

In [6]:
greatestval = 0
#we'll start with left/rights
for i in range(0,16):
    for j in range(0,19):
        listy = []
        listy += arr2[i,j],arr2[i+1,j],arr2[i+2,j],arr2[i+3,j]
        arty = np.array(listy)
        if np.prod(arty)>greatestval:
            greatestval= np.prod(arty)
print(greatestval)

51267216


In [7]:
#now up downs
for i in range(0,19):
    for j in range(0,16):
        listy = []
        listy += arr2[i,j],arr2[i,j+1],arr2[i,j+2],arr2[i,j+3]
        arty = np.array(listy)
        if np.prod(arty)>greatestval:
            greatestval = np.prod(arty)
print(greatestval)

51267216


In [8]:
#now leftup to rightdown diagonals
for i in range(0,16):
    for j in range(0,16):
        listy = []
        listy += arr2[i,j],arr2[i+1,j+1],arr2[i+2,j+2],arr2[i+3,j+3]
        arty = np.array(listy)
        if np.prod(arty)>greatestval:
            greatestval = np.prod(arty)
print(greatestval)

51267216


In [9]:
for i in range(3,19):
    for j in range(0,16):
        listy = []
        listy += arr2[i,j],arr2[i-1,j+1],arr2[i-2,j+2],arr2[i-3,j+3]
        arty = np.array(listy)
        if np.prod(arty)>greatestval:
            greatestval = np.prod(arty)
print('Answer to problem 11:', greatestval)

Answer to problem 11: 70600674


Problem 12 

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

In [14]:
def generatetriangle(input1):
    i=1
    output = 0
    while i<=input1:
        output+=i
        i+=1
    return output
print(generatetriangle(7))

28


In [2]:
from functions import divisor_count

In [5]:
i=1
maxnum=0
beta=0
target = 500
while maxnum<target:
    beta+=i
    alpha=divisor_count(beta)
    if alpha>maxnum:
        maxnum=alpha
    i+=1
print("Answer to problem 12:", beta)

Answer to problem 12: 76576500


Problem 13 

Work out the first ten digits of the sum of the following one-hundred 50-digit numbers.

[List of numbers omitted for readability]

In [6]:
addthese = '\
37107287533902102798797998220837590246510135740250\
46376937677490009712648124896970078050417018260538\
74324986199524741059474233309513058123726617309629\
91942213363574161572522430563301811072406154908250\
23067588207539346171171980310421047513778063246676\
89261670696623633820136378418383684178734361726757\
28112879812849979408065481931592621691275889832738\
44274228917432520321923589422876796487670272189318\
47451445736001306439091167216856844588711603153276\
70386486105843025439939619828917593665686757934951\
62176457141856560629502157223196586755079324193331\
64906352462741904929101432445813822663347944758178\
92575867718337217661963751590579239728245598838407\
58203565325359399008402633568948830189458628227828\
80181199384826282014278194139940567587151170094390\
35398664372827112653829987240784473053190104293586\
86515506006295864861532075273371959191420517255829\
71693888707715466499115593487603532921714970056938\
54370070576826684624621495650076471787294438377604\
53282654108756828443191190634694037855217779295145\
36123272525000296071075082563815656710885258350721\
45876576172410976447339110607218265236877223636045\
17423706905851860660448207621209813287860733969412\
81142660418086830619328460811191061556940512689692\
51934325451728388641918047049293215058642563049483\
62467221648435076201727918039944693004732956340691\
15732444386908125794514089057706229429197107928209\
55037687525678773091862540744969844508330393682126\
18336384825330154686196124348767681297534375946515\
80386287592878490201521685554828717201219257766954\
78182833757993103614740356856449095527097864797581\
16726320100436897842553539920931837441497806860984\
48403098129077791799088218795327364475675590848030\
87086987551392711854517078544161852424320693150332\
59959406895756536782107074926966537676326235447210\
69793950679652694742597709739166693763042633987085\
41052684708299085211399427365734116182760315001271\
65378607361501080857009149939512557028198746004375\
35829035317434717326932123578154982629742552737307\
94953759765105305946966067683156574377167401875275\
88902802571733229619176668713819931811048770190271\
25267680276078003013678680992525463401061632866526\
36270218540497705585629946580636237993140746255962\
24074486908231174977792365466257246923322810917141\
91430288197103288597806669760892938638285025333403\
34413065578016127815921815005561868836468420090470\
23053081172816430487623791969842487255036638784583\
11487696932154902810424020138335124462181441773470\
63783299490636259666498587618221225225512486764533\
67720186971698544312419572409913959008952310058822\
95548255300263520781532296796249481641953868218774\
76085327132285723110424803456124867697064507995236\
37774242535411291684276865538926205024910326572967\
23701913275725675285653248258265463092207058596522\
29798860272258331913126375147341994889534765745501\
18495701454879288984856827726077713721403798879715\
38298203783031473527721580348144513491373226651381\
34829543829199918180278916522431027392251122869539\
40957953066405232632538044100059654939159879593635\
29746152185502371307642255121183693803580388584903\
41698116222072977186158236678424689157993532961922\
62467957194401269043877107275048102390895523597457\
23189706772547915061505504953922979530901129967519\
86188088225875314529584099251203829009407770775672\
11306739708304724483816533873502340845647058077308\
82959174767140363198008187129011875491310547126581\
97623331044818386269515456334926366572897563400500\
42846280183517070527831839425882145521227251250327\
55121603546981200581762165212827652751691296897789\
32238195734329339946437501907836945765883352399886\
75506164965184775180738168837861091527357929701337\
62177842752192623401942399639168044983993173312731\
32924185707147349566916674687634660915035914677504\
99518671430235219628894890102423325116913619626622\
73267460800591547471830798392868535206946944540724\
76841822524674417161514036427982273348055556214818\
97142617910342598647204516893989422179826088076852\
87783646182799346313767754307809363333018982642090\
10848802521674670883215120185883543223812876952786\
71329612474782464538636993009049310363619763878039\
62184073572399794223406235393808339651327408011116\
66627891981488087797941876876144230030984490851411\
60661826293682836764744779239180335110989069790714\
85786944089552990653640447425576083659976645795096\
66024396409905389607120198219976047599490197230297\
64913982680032973156037120041377903785566085089252\
16730939319872750275468906903707539413042652315011\
94809377245048795150954100921645863754710598436791\
78639167021187492431995700641917969777599028300699\
15368713711936614952811305876380278410754449733078\
40789923115535562561142322423255033685442488917353\
44889911501440648020369068063960672322193204149535\
41503128880339536053299340368006977710650566631954\
81234880673210146739058568557934581403627822703280\
82616570773948327592232845941706525094512325230608\
22918802058777319719839450180888072429661980811197\
77158542502016545090413245809786882778948721859617\
72107838435069186155435662884062257473692284509516\
20849603980134001723930671666823555245252804609722\
53503534226472524250874054075591789781264330331690'

In [7]:
print(len(addthese))

5000


In [8]:
print(5000/50)
print(len(addthese[0:50]))

100.0
50


In [9]:
x = 0
listy = []
while x <= 5000 - 50:
    listy += [int(addthese[x:x+50])]
    x+=50
print(sum(listy))

5537376230390876637302048746832985971773659831892672


In [11]:
print("Answer to Problem 13:", str(sum(listy))[0:10])

Answer to Problem 13: 5537376230


Problem 14

The following iterative sequence is defined for the set of positive integers:

n → n/2 (n is even)<br>
n → 3n + 1 (n is odd)

Using the rule above and starting with 13, we generate the following sequence:

13 → 40 → 20 → 10 → 5 → 16 → 8 → 4 → 2 → 1<br>
It can be seen that this sequence (starting at 13 and finishing at 1) contains 10 terms. Although it has not been proved yet <br>(Collatz Problem), it is thought that all starting numbers finish at 1.

Which starting number, under one million, produces the longest chain?

NOTE: Once the chain starts the terms are allowed to go above one million.

In [12]:
def collatz(x):
    n=1
    while x!=1:
        if x%2==0:
            x=x/2
        elif x%2==1:
            x=(3*x)+1
        n+=1
    return n
print(collatz(13))

10


In [19]:
b=0
for a in range(1,1000000):
    c=collatz(a)
    if c>b:
        b=c
        maxnum=a
print("Answer to Problem 14:", maxnum)

Answer to Problem 14: 837799


Problem 15

Starting in the top left corner of a 2×2 grid, and only being able to move to the right and down, there are exactly 6 routes to the bottom right corner.


How many such routes are there through a 20×20 grid?

Problem 15 is just a combinatorics problem which does not require coding. The solution is 40 choose 20.

In [22]:
print("Answer to Problem 15:", math.comb(40,20))

Answer to Problem 15: 137846528820


Problem 16

215 = 32768 and the sum of its digits is 3 + 2 + 7 + 6 + 8 = 26.

What is the sum of the digits of the number 21000?

In [23]:
2**1000

10715086071862673209484250490600018105614048117055336074437503883703510511249361224931983788156958581275946729175531468251871452856923140435984577574698574803934567774824230985421074605062371141877954182153046474983581941267398767559165543946077062914571196477686542167660429831652624386837205668069376

In [29]:
stringy1 = '10715086071862673209484250490600018105614048117055336074437503883703510511249361224931983788156958581275946729175531468251871452856923140435984577574698574803934567774824230985421074605062371141877954182153046474983581941267398767559165543946077062914571196477686542167660429831652624386837205668069376'

print(len(stringy1))
n=0
for x in range(0,302):
    n+=int(stringy1[x])
print("Answer to Problem 16:", n)

302
Answer to Problem 16: 1366


Problem 17

If the numbers 1 to 5 are written out in words: one, two, three, four, five, then there are 3 + 3 + 5 + 4 + 4 = 19 letters used in total.

If all the numbers from 1 to 1000 (one thousand) inclusive were written out in words, how many letters would be used?


NOTE: Do not count spaces or hyphens. For example, 342 (three hundred and forty-two) contains 23 letters and 115 (one hundred and<br> fifteen) contains 20 letters. The use of "and" when writing out numbers is in compliance with British usage.

In [33]:
strings1 =['','one','two','three','four','five','six','seven','eight','nine']
strings2=['twenty','thirty','forty','fifty','sixty','seventy','eighty','ninety']
strings3=['hundred','and','thousand']
strings4=['ten','eleven','twelve','thirteen','fourteen','fifteen','sixteen','seventeen','eighteen','nineteen']
m=0
for a in range(0,10):
    m+=len(strings1[a])
    #print(strings1[a])
n=0
for b in range(0,10):
    n+=len(strings4[b])
    #print(strings4[b])
# print(m)
# print(n)
o=0
for c in range(0,8):
    for d in range(0,10):
        o+=(len(strings2[c])+len(strings1[d]))
        #print(strings2[c]+strings1[d])
# print(o)
p=0
s=0
for i in range(1,10):
    for j in range(0,8):
        for k in range(0,10):
            p+=len(strings1[i])+len(strings3[0])+len(strings3[1])+len(strings2[j])+len(strings1[k])
            
r=0
for l in range(1,10):
    r+=len(strings1[l])+len(strings3[0])
    #print(strings1[l]+strings3[0])
# print(p)
q=11
# print(q)
# print(r)
t=0
for e in range(1,10):
    for f in range(1,10):
        s+=len(strings1[e])+len(strings3[0])+3+len(strings1[f])
        #print(strings1[e]+strings3[0]+strings1[f])
    for g in range(0,10):
        t+=len(strings1[e])+len(strings3[0])+3+len(strings4[g])
        #print(strings1[e]+strings3[0]+strings4[g])
# print(s)
# print(t)
print('Answer to Problem 17 :', m+n+o+p+q+r+s+t)

Answer to Problem 17 : 21124


Problem 18

Maxiumum Path Sum I

By starting at the top of the triangle below and moving to adjacent numbers on the row below, the maximum total from top to bottom is 23.

<span style="color:red">3</span><br>
<span style="color:red">7</span> 4<br>
2 <span style="color:red">4</span> 6<br>
8 5 <span style="color:red">9</span> 3

That is, 3 + 7 + 4 + 9 = 23.

Find the maximum total from top to bottom of the triangle below:

75<br>
95 64<br>
17 47 82<br>
18 35 87 10<br>
20 04 82 47 65<br>
19 01 23 75 03 34<br>
88 02 77 73 07 63 67<br>
99 65 04 28 06 16 70 92<br>
41 41 26 56 83 40 80 70 33<br>
41 48 72 33 47 32 37 16 94 29<br>
53 71 44 65 25 43 91 52 97 51 14<br>
70 11 33 28 77 73 17 78 39 68 17 57<br>
91 71 52 38 17 14 91 43 58 50 27 29 48<br>
63 66 04 68 89 53 67 30 73 16 69 87 40 31<br>
04 62 98 27 23 09 70 98 73 93 38 53 60 04 23

NOTE: As there are only 16384 routes, it is possible to solve this problem by trying every route. However, Problem 67, is the same challenge with a triangle containing one-hundred rows; it cannot be solved by brute force, and requires a clever method! ;o)

In [2]:
smalltri = '\
75 \
95 64 \
17 47 82 \
18 35 87 10 \
20 04 82 47 65 \
19 01 23 75 03 34 \
88 02 77 73 07 63 67 \
99 65 04 28 06 16 70 92 \
41 41 26 56 83 40 80 70 33 \
41 48 72 33 47 32 37 16 94 29 \
53 71 44 65 25 43 91 52 97 51 14 \
70 11 33 28 77 73 17 78 39 68 17 57 \
91 71 52 38 17 14 91 43 58 50 27 29 48 \
63 66 04 68 89 53 67 30 73 16 69 87 40 31 \
04 62 98 27 23 09 70 98 73 93 38 53 60 04 23 '

In [3]:
tinytri = '\
3 \
7 4 \
2 4 6 \
8 5 9 3 '

In [4]:
print(len(smalltri))
print(tinytri)

360
3 7 4 2 4 6 8 5 9 3 


In [5]:
#So here I separate out the "literal" variable type into a list of numbers
x = 0
listy =[]
while x <= len(smalltri)-3:
    listy += [int(smalltri[x:x+3])]
    x+=3
print(len(listy))
print(listy[len(listy)-1])

120
23


In [6]:
print(listy)

[75, 95, 64, 17, 47, 82, 18, 35, 87, 10, 20, 4, 82, 47, 65, 19, 1, 23, 75, 3, 34, 88, 2, 77, 73, 7, 63, 67, 99, 65, 4, 28, 6, 16, 70, 92, 41, 41, 26, 56, 83, 40, 80, 70, 33, 41, 48, 72, 33, 47, 32, 37, 16, 94, 29, 53, 71, 44, 65, 25, 43, 91, 52, 97, 51, 14, 70, 11, 33, 28, 77, 73, 17, 78, 39, 68, 17, 57, 91, 71, 52, 38, 17, 14, 91, 43, 58, 50, 27, 29, 48, 63, 66, 4, 68, 89, 53, 67, 30, 73, 16, 69, 87, 40, 31, 4, 62, 98, 27, 23, 9, 70, 98, 73, 93, 38, 53, 60, 4, 23]


In [9]:
smalltri1 = np.zeros((15,15), dtype = int)
x = 0
for i in range(0,15):
    for j in range (0,i+1):
        smalltri1[i,j] = listy[x]
        x+=1
print(smalltri1)

[[75  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [95 64  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [17 47 82  0  0  0  0  0  0  0  0  0  0  0  0]
 [18 35 87 10  0  0  0  0  0  0  0  0  0  0  0]
 [20  4 82 47 65  0  0  0  0  0  0  0  0  0  0]
 [19  1 23 75  3 34  0  0  0  0  0  0  0  0  0]
 [88  2 77 73  7 63 67  0  0  0  0  0  0  0  0]
 [99 65  4 28  6 16 70 92  0  0  0  0  0  0  0]
 [41 41 26 56 83 40 80 70 33  0  0  0  0  0  0]
 [41 48 72 33 47 32 37 16 94 29  0  0  0  0  0]
 [53 71 44 65 25 43 91 52 97 51 14  0  0  0  0]
 [70 11 33 28 77 73 17 78 39 68 17 57  0  0  0]
 [91 71 52 38 17 14 91 43 58 50 27 29 48  0  0]
 [63 66  4 68 89 53 67 30 73 16 69 87 40 31  0]
 [ 4 62 98 27 23  9 70 98 73 93 38 53 60  4 23]]


Let's start with a brute force method, then look for more efficient methods.<br>
There was already a problem regarding the number of possible paths down a triangle<br>

I know that I am looking at a series of binary choices:<br>
2^14<br>

I can think of many ways to make it more likely to find a good path. However I can't think of any to guarantee the greatest path.


In [10]:
print('Number of possible paths:',2**14)
print('Imagine an array of length fourteen each entry of which can contain a 1 or 0')

Number of possible paths: 16384
Imagine an array of length fourteen each entry of which can contain a 1 or 0


In [11]:
def binarraygenerator(n):
    binarr = np.zeros(14,dtype=int)
    i = 0
    while n > 2**i:
        i+=1
    while i > -1:
        if n >= 2**i:
            binarr[-i-1]=1
            n = n-(2**i)
        i-=1
    return binarr

In [14]:
#reviewing this code it looks like this function is essentially counting in binary upto 2^14
print(binarraygenerator(4))
print(binarraygenerator(1074))

[0 0 0 0 0 0 0 0 0 0 0 1 0 0]
[0 0 0 1 0 0 0 0 1 1 0 0 1 0]


In [15]:
greatestsum = 0
bestarr= np.empty(15,dtype=int)
binarr = np.empty(14,dtype=int)

In [16]:
for i in range (0,2**14-1):
    currarr = np.zeros(15,dtype=int)
    currarr[0]=75
    x = binarraygenerator(i)
    k = 0
    for j in range(1,15):
        k+= x[j-1]
        currarr[j] = smalltri1[j,k]
    if sum(currarr)>greatestsum:
        greatestsum = sum(currarr)
        bestarr[:]=currarr
        binarr[:]=x
print('Answer to problem 18:', greatestsum)

Answer to problem 18: 1074


Problem 19

Sundays in the 20th Century

You are given the following information, but you may prefer to do some research for yourself.

1 Jan 1900 was a Monday. 

Thirty days has September,

April, June and November.

All the rest have thirty-one,

Saving February alone,

Which has twenty-eight, rain or shine.

And on leap years, twenty-nine.

A leap year occurs on any year evenly divisible by 4, but not on a century unless it is divisible by 400.
How many Sundays fell on the first of the month during the twentieth century (1 Jan 1901 to 31 Dec 2000)?

In [17]:
months = ['January', 'February', 'March', 'April', 'May', 'June', 'July',
          'August', 'September', 'October', 'November', 'December']
daysineachmonth = np.array([31,28,31,30,31,30,31,31,30,31,30,31])
daysoftheweek =['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
startyear = 1901
startday = 1
modmonths = (daysineachmonth%7)
print(modmonths)

[3 0 3 2 3 2 3 3 2 3 2 3]


In [19]:
startdate = [months[0],startday,startyear]
enddate = [months[11],daysineachmonth[11],2000]
print(startdate)
print(enddate)

['January', 1, 1901]
['December', 31, 2000]


In [18]:
totalsundays = 0
counter = 1
sundays =[]
for i in range(1,101):
    for j in range(0,12):
        if counter%7==6:
            totalsundays+=1
            #print('1st of', months[j], 1900+i)
        if j == 1 and i%4 == 0:
            counter +=1
        counter+=modmonths[j]
        
print(totalsundays)
print(counter)

171
2926


Problem 20

Factorial Digit Sum

n! means n × (n − 1) × ... × 3 × 2 × 1

For example, 10! = 10 × 9 × ... × 3 × 2 × 1 = 3628800,
and the sum of the digits in the number 10! is 3 + 6 + 2 + 8 + 8 + 0 + 0 = 27.

Find the sum of the digits in the number 100!



In [25]:
numberstring = str(math.factorial(100))
answer = 0
for i in range(0,len(numberstring)-1):
    answer+=int(numberstring[i])
print("Answer to Problem 20:", answer)

Answer to Problem 20: 648


Thank you for reading my solutions!

-Everett