Run #2

Coin sums


Problem 31
In the United Kingdom the currency is made up of pound (£) and pence (p). There are eight coins in general circulation:

1p, 2p, 5p, 10p, 20p, 50p, £1 (100p), and £2 (200p).
It is possible to make £2 in the following way:

1×£1 + 1×50p + 2×20p + 1×5p + 1×2p + 3×1p
How many different ways can £2 be made using any number of coins?

In [2]:
import numpy as np
from numpy import linalg

100 1 pence coins
1 2 pound coin

In [3]:
C = np.array([1,2,5,10,20,50,100,200])

In [4]:
print(C)
C = np.transpose(C.reshape(8,1))
print(C)

[  1   2   5  10  20  50 100 200]
[[  1   2   5  10  20  50 100 200]]


In [16]:
print(C[0,1])

2


In [17]:
A = np.array([200,0,0,0,0,0,0,0])
print(A)
print(np.transpose(A))

[200   0   0   0   0   0   0   0]
[200   0   0   0   0   0   0   0]


In [18]:
A = np.transpose(A.reshape(1,8))
print(A)

[[200]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]]


In [19]:
print(np.dot(C,A))

[[200]]


In [20]:
print(C)

[[  1   2   5  10  20  50 100 200]]


In [21]:
100*50*40*20*10*2*1

80000000

In [22]:
100+50+40+20+10+2+1

223

In [25]:
print(C)
print(np.shape(C))

[[  1   2   5  10  20  50 100 200]]
(1, 8)


In [29]:
Coin_val = C
print(Coin_val)
D = np.array([0,0,0,0,0,0,0,0])
D.reshape(1,8)
print(D)

[[  1   2   5  10  20  50 100 200]]
[0 0 0 0 0 0 0 0]


In [32]:
print(np.vstack((Coin_val,D)))

[[  1   2   5  10  20  50 100 200]
 [  0   0   0   0   0   0   0   0]]


In [43]:
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)
#Problem 31 Coin Sums
A = np.array([1,2,5,10,20,50,100,200])
for i in range(1,201):
    A  = np.vstack((A,np.array([1,0,0,0,0,0,0,0])))
    for j in range(1,8):
        if i<A[0,j]:
            A[i,j] = A[i,j-1]
        elif i==A[0,j]:
            A[i,j]=1+A[i,j-1]
        else:
            A[i,j]=A[i,j-1]+A[(i-A[0,j]),j]
print(A)

[[    1     2     5    10    20    50   100   200]
 [    1     1     1     1     1     1     1     1]
 [    1     2     2     2     2     2     2     2]
 [    1     2     2     2     2     2     2     2]
 [    1     3     3     3     3     3     3     3]
 [    1     3     4     4     4     4     4     4]
 [    1     4     5     5     5     5     5     5]
 [    1     4     6     6     6     6     6     6]
 [    1     5     7     7     7     7     7     7]
 [    1     5     8     8     8     8     8     8]
 [    1     6    10    11    11    11    11    11]
 [    1     6    11    12    12    12    12    12]
 [    1     7    13    15    15    15    15    15]
 [    1     7    14    16    16    16    16    16]
 [    1     8    16    19    19    19    19    19]
 [    1     8    18    22    22    22    22    22]
 [    1     9    20    25    25    25    25    25]
 [    1     9    22    28    28    28    28    28]
 [    1    10    24    31    31    31    31    31]
 [    1    10    26    34    34

    Oh Jeez
   

In [15]:
import sys
print(sys.version)

3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 12:04:33) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]


Isn't the point of money just to make us feel small?